(defun color-theme-butcher ()
  "Color theme by Pavel Nikitin."
  (interactive)
  (color-theme-install
   '(color-theme-butcher
     ((background-color . "#101010")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "#A7A7A7")
      (foreground-color . "#F8F8F8")
      (mouse-color . "sienna1"))
     (default ((t (:background "#101010" :foreground "#F8F8F8"))))
     (blue ((t (:foreground "blue"))))
     (bold ((t (:bold t))))
     (bold-italic ((t (:bold t))))
     (border-glyph ((t (nil))))
     (buffers-tab ((t (:background "#101010" :foreground "#F8F8F8"))))
     (gui-element ((t (:background "#D4D0C8" :foreground "black"))))
     (highlight ((t (:background "#222222"))))
     (highline-face ((t (:background "SeaGreen"))))
     (region ((t (:background "#404040"))))
     (modeline ((t (:background "#101010" :foreground "#AEAEAE" :box (:line-width 1 :color "#AEAEAE")))))
     (modeline-inactive ((t (:background "#101010" :foreground "#606060" :box (:line-width 1 :color "#606060")))))
     (italic ((t (nil))))
     (left-margin ((t (nil))))
     (text-cursor ((t (:background "yellow" :foreground "black"))))
     (toolbar ((t (nil))))
     (underline ((nil (:underline nil))))
     (zmacs-region ((t (:background "snow" :foreground "ble")))))))
